version: '3'
services:
  api_flask_app:
    container_name: "APIFlask-service"
    build:
      context: ${LOCAL_PATH}/DataProcessor/api_flask_env
    volumes:
      - data_volume:/app/data
    ports:
      - "5000:5000"
    networks:
      - my_network
    # network_mode: "host"
    depends_on:
      - db
    environment:
      - FLASK_RUN_HOST=0.0.0.0

  flask_app:
    container_name: "Flask-service"
    build:
      context: ${LOCAL_PATH}/DataProcessor/flask_env
    volumes:
      - data_volume:/app/data
    ports:
      - "8001:8001"
    networks:
      - my_network
    # network_mode: "host"


  fast_api_flask:
    container_name: "FastAPI-service"
    build:
      context: ${LOCAL_PATH}/DataProcessor/fast_api_env
    volumes:
      - data_volume:/app/data
    ports:
      - "8002:8002"
    networks:
      - my_network
    # network_mode: "host"
    depends_on:
      - db

  django_flask:
    container_name: "Django-service"
    build:
      context: ${LOCAL_PATH}/DataProcessor/django_env
    volumes:
      - data_volume:/app/data
    ports:
      - "8000:8000"
    networks:
      - my_network
    # network_mode: "host"
    depends_on:
      - postgres-db

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: my_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network
    # network_mode: "host"

  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - data_volume:/app/data
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mypassword'
      MYSQL_ROOT_PASSWORD: 'myrootpassword'
    networks:
      - my_network

  postgres-db:
    image: postgres:latest
    container_name: PostgresDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - data_volume:/app/data
    environment:
      POSTGRES_DB: 'mydatabase'
      POSTGRES_USER: 'myuser'
      POSTGRES_PASSWORD: 'mypassword'
    networks:
      - my_network

volumes:
  data_volume:

networks:
  my_network:
